all invocations of PyCObject_Check(pystate) should return a meaningful exception
without this we see:
 SystemError: error return without exception set
which is not very helpful

Fixes #281

git-svn-id: http://svn.calendarserver.org/repository/calendarserver/PyKerberos/trunk@3004 e27351fd-9f3e-4f54-a53b-843176b1656c